on:
  pull_request:  

jobs:
  HossamEsam:  
    runs-on: ubuntu-latest  
    steps:
      - name: Install Java and Maven
      - uses: actions/setup-java
         with:
          java-version: '22'  
          distribution: 'temurin'
      - name: Run your automation scrip
        run: |
          mvn test -DsuiteXmlFile=src\test\resources\Runner\Runner.xml
