name: Practice
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Java and Maven
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: adopt
      - name: Print Working Directory
        run: pwd
      - name: Set up Maven 3.9.5
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.5  
      - name: Run your automation script
        run: |
          mvn test Runner.xml
          
          #cd practice
          #mvn package
          
          #mvn test -DsuiteXmlFile=Runner.xml
